WINDOW_SIZE_X = 1600
WINDOW_SIZE_Y = 800
SIM_BOARD_SIZE_X = 800
SIM_BOARD_SIZE_Y = 800

FPS = 90

POPULATION = 2
FOOD_INIT_NUMBER = 20
DIE_TYPE_COLLISION = POPULATION + FOOD_INIT_NUMBER + 10
RECOVERY_TIME = 300  # dependent on fps
